# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Workshop-2
email: weijia.tang.18@dartmouth.edu
description: example site for workshop-2
baseurl: "/startjekyll" # the subpath of your site, e.g. /blog
url: "http://wtang1996/github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  wtang1996

# Build settings
markdown: kramdown

include: ['_pages']

sass:
  sass_dir: _scss
